### PR TITLE
Support building on macOS

### LINKED ISSUE #28: Doesn't build on OSX
Trying to build this package locally on a Macbook and I get the following error:
```
error[E0432]: unresolved import `nix::sys::epoll::*`
  --> src/lib.rs:64:5
   |
64 | use nix::sys::epoll::*;
   |     ^^^^^^^^^^^^^^^^^^^ Could not find `epoll` in `nix::sys`
```

Version Info:
```
$ rustc --version
rustc 1.13.0

cargo 0.13.0 (eca9e15 2016-11-01)
```

### PR DESCRIPTION
**Pull request by zaynetro**
Allow building the project on macOS.

Fixes #28

### CODE REVIEW

**Comment by posborne** [comment]
Thanks, can you add OSX to the Travis build config?  This will help us avoid regressions moving forward.

**Comment by zaynetro** [comment]
I am not familiar with Travis. Thus, I can do a change based on this pull request: https://github.com/rust-embedded/rust-i2cdev/pull/22 

To my understanding we first tell Travis to build on osx by adding the following lines to `.travis.yml`:

```
os:
 - linux
 - osx
```

The only thing I am not sure is whether I need to include conditional after_success actions similar to this: https://github.com/rust-embedded/rust-i2cdev/pull/22/files#diff-354f30a63fb0907d4ad57269548329e3R17

**Comment by zaynetro** [comment]
Apparently, `travis-cargo` doesn't work on osx: [ref](https://github.com/huonw/travis-cargo/issues/70)

**Comment by zaynetro** [comment]
OK. I was able to resolve `travis-cargo` not working on osx. Thanks to this: https://github.com/huonw/travis-cargo/pull/71

**Comment by posborne** [comment]
> @posborne Shall we do after_success steps only for linux env?
 
Yeah, that probably makes sense.  Thanks for hunting that down.

**Comment by zaynetro** [comment]
@posborne Done!

**Pull request merged**
