### PR TITLE
Add support for wasm32-wasi compilation target

### PR DESCRIPTION
**Pull request by rahul-thakoor**
Related to #64

### CODE REVIEW

**Review by eldruin — APPROVED** [review]
Sounds fine to me. Thanks!

**Comment by rahul-thakoor** [comment]
@eldruin  @ryankurte any chance getting this merged please?

**Comment by eldruin** [comment]
Hmm, our CI is broken due to deps breaking the current MSRV but we should deal with that in a separate issue. Let's merge this.
Thank you @rahul-thakoor and sorry for the delay.

**Comment by rahul-thakoor** [comment]
thanks

**Pull request merged**
