### PR TITLE
Readme updates

### PR DESCRIPTION
**Pull request by posborne**
CC @varzac @nastevens 

Please review.  I am now running my on homu bot @rust-embedded-bot that you should be able to use normal homu commands with (e.g. r+).

### CODE REVIEW

**Comment by posborne** [comment]
Testing... not sure this thing is 100% working yet...

@rust-embedded-bot r=posborne

**Comment by posborne** [comment]
@rust-embedded-bot retry

**Comment by posborne** [comment]
@rust-embedded-bot r+

**Comment by posborne** [comment]
@rust-embedded-bot r+

**Comment by posborne** [comment]
Hmmm, will need to debug the final part (travis notifying bot that build passed/failed).  Looks like homu is getting hit from Travis but we got something left to solve:

```
2016-05-01T05:46:26.765007+00:00 app[web.1]: authorization failed for PullReqState:rust-embedded/rust-sysfs-gpio#15(approved_by=posborne, priority=0, status=pending), maybe the repo has the wrong travis token? ... (redacted) ...
```

**Comment by varzac** [comment]
:+1:

**Comment by nastevens** [comment]
@rust-embedded-bot r+

**Comment by posborne** [comment]
@rust-embedded-bot retry

**Comment by posborne** [comment]
@rust-embedded-bot r-

**Comment by posborne** [comment]
@rust-embedded-bot r=nastevens

**Comment by posborne** [comment]
@rust-embedded-bot r=nastevens

**Comment by posborne** [comment]
It's working :tada:

**Pull request merged**
