### PR TITLE
Bump async dependencies

### PR DESCRIPTION
**Pull request by oll3**
Bumped tokio, mio and futures to recent versions. Took some inspiration from the previous gpio-cdev tokio work and also picked some parts from #60.

Not tested the mio parts but the tokio example (from #60) seems to be working.

### CODE REVIEW

**Comment by eldruin** [comment]
Thank you very much!
CI failed now just because of an unused import.
Could somebody else review this @rust-embedded/embedded-linux?
Maybe @ryankurte?

**Comment by oll3** [comment]
> CI failed now just because of an unused import.

Fixed the unused import (and squashed it to the previous commit).

**Comment by oll3** [comment]
> > CI failed now just because of an unused import.
> 
> Fixed the unused import (and squashed it to the previous commit).

...and another fix for the mio-evented feature added :eyes:

**Review by posborne — COMMENTED** [review]
Changes LGTM, I think the only thing I would like to see updated is to bump the version in Cargo.toml and look to identify the new MSRV as I suspect these changes impact the minimum supported rust version.

**Comment by oll3** [comment]
> Changes LGTM, I think the only thing I would like to see updated is to bump the version in Cargo.toml and look to identify the new MSRV as I suspect these changes impact the minimum supported rust version.

Tokio has MSVR at 1.45 and rust-sysfs-gpio says 1.46 in README.md so it's probably fine as it is.
Should bumping of crate version be in this PR, 0.6.0?

**Review by eldruin — COMMENTED** [review]
Great!
I have a couple of details left to do before the release so I would do the version bump in a separate PR.
@oll3 could you also add an entry about these updates to the changelog?
Then I would merge this.

**Review by eldruin — APPROVED** [review]
Thank you for your work!
bors r+

**Pull request merged**
