### PR TITLE
Removed try! macro in favour of the ? operator

### PR DESCRIPTION
**Pull request by Razican**
This formats the code like #31, but additionally removes the `try!` macro. I created separate pull requests just in case you want only the formatting and not the `?` operator.

### CODE REVIEW

**Comment by posborne** [comment]
Hi @Razican can you bump the version in CI needed to support `?` (0.15 IIRC?).  I pushed back on breaking older rust for some time but would be OK with it now, although I would consider the change breaking (and as such require a major version number bump according to semver).

**Comment by Razican** [comment]
I rebased. This should also fix #31

**Comment by posborne** [comment]
> I rebased. This should also fix #31

Can you take a look at the OSX build failure.  We are mostly just ignoring the crate on OSX it but I would like CI passing.  Feel free to set OSX to stable and I think that should fix.

**Comment by Razican** [comment]
I think I fixed the issue, forgot to change the minimum CI Rust version.

**Pull request merged**
